# This file contains "hidden jobs" that are not executed by the runner
# but are included as needed using the extend keyword. Note that we cannot
# use a `yaml anchor` as this is being sourced from a different file

.adev_vars:
  variables:
    CICD_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-Role
    ECS_REFRESH_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-ECS-RefreshRunnerRole
    LAMBDA_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-lambda
    AWS_REGION: us-east-1
    ENVIRONMENT: adev
    gitlab_registry_token: $adev_gitlab_registry_token
    ECS_CLUSTER_NAME: "bevel-adev"
    
.astg_vars:
  variables:
    CICD_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-Role
    ECS_REFRESH_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-ECS-RefreshRunnerRole
    LAMBDA_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-lambda
    AWS_REGION: us-east-1
    ENVIRONMENT: astg
    gitlab_registry_token: $astg_gitlab_registry_token
    ECS_CLUSTER_NAME: "bevel-astg" 

.aprd_vars:
  variables:
    CICD_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-Role
    ECS_REFRESH_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-ECS-RefreshRunnerRole
    LAMBDA_ROLE_ARN: arn:aws:iam::111111111111:role/bevel-cicd-lambda
    AWS_REGION: us-east-1
    ENVIRONMENT: aprd
    gitlab_registry_token: $aprd_gitlab_registry_token
    ECS_CLUSTER_NAME: "bevel-aprd"                                                                      
